# Generated by Django 4.0.5 on 2022-08-04 04:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre', unique=True)),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen')),
                ('portada', models.CharField(max_length=100, verbose_name='Portada')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
            ],
        ),
    ]
