# Generated by Django 4.0.5 on 2022-08-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Genero')),
                ('idgenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.movie')),
            ],
        ),
    ]
