# Generated by Django 4.0.5 on 2022-08-04 05:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='titulo', unique=True, verbose_name='Slug'),
        ),
    ]
