# Generated by Django 4.0.5 on 2022-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imagen',
            field=models.CharField(max_length=200, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='portada',
            field=models.CharField(max_length=200, verbose_name='Portada'),
        ),
    ]
