# Generated by Django 4.0.5 on 2022-08-04 06:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_alter_movie_imagen_alter_movie_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='pelicula',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='titulo', unique=True, verbose_name='Slug'),
        ),
    ]
