# Generated by Django 4.0.5 on 2022-08-04 06:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_genero_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='pelicula',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='idgenero', verbose_name='Pelicula'),
        ),
    ]
