# Generated by Django 4.0.5 on 2022-08-04 21:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_generomovie_rename_id_movie_idmovie_remove_genero_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generomovie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='idmovie', verbose_name='Slug'),
        ),
    ]
