# Generated by Django 4.0.5 on 2022-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_generomovie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imagen',
            field=models.TextField(verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='portada',
            field=models.TextField(verbose_name='Portada'),
        ),
    ]
