# Generated by Django 4.0.5 on 2022-08-13 07:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_generomovie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Portada'),
        ),
    ]
